### ISSUE TITLE
Add to album dialog not working

### ISSUE THREAD

**Issue by muety** [photoprism/photoprism-mobile#26]
**How to reproduce:**
1. Select one or more picture on photos page
2. Click plus (+) sign

**Expected:** Dialog to select an album appears

**Actual:** Background is darkened, but no dialog shows up.

**Comment by muety** [comment]
The following exception is thrown: https://pastebin.com/SknPtbY1

**Comment by spaibs** [comment]
Thank you very much! Unfortunately I can't reproduce the issue. What phone and version are you using?

**Comment by muety** [comment]
A (emulated) Pixel 2 with Android API level 24 and latest master branch.

**Comment by spaibs** [comment]
Ah, thanks! I could now reproduce it and will merge the pull request. Thank you for the help!
