### ISSUE TITLE
Improve scroll performance of photo view

### ISSUE THREAD

**Issue by spaibs** [photoprism/photoprism-mobile#46]

**Comment by thielepaul** [comment]
the performance of the photo gridview is improved via #47

**Comment by timdonovanuk** [comment]
I'm using an nvme with read performance of 5000 MB/s, and my database queries in ~ 60ms each scroll.  I still quite often hit a ton of grey boxes, and I'm not sure where/how to start troubleshooting

![image](https://user-images.githubusercontent.com/8156439/116783786-a080c580-aa88-11eb-9de4-ee8770aaf804.png)

**Comment by timdonovanuk** [comment]
Hm....I just imported a load of photos from iCloud. I suspect photoprism is loading full video files now as I scroll through, as I can see network requests to things like:

http://photos.home:2342/api/v1/videos/9980f0d0ee04af80456526ff38ee5a7c1f08cf01/public/avc

Network tab in chrome shows it's downloading the full video files for this. Not surprised things are getting laggy!
